#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2024 OpenWrt.Org

START=99
USE_PROCD=1
size="$(df -k | awk '/\/overlay$/ {sub(/K$/, "", $4); print $4}')"
[ -z "$size" ] && size="$(df -k /usr/bin | awk 'NR==2 {print $(NF-2) }')"
curltest=`which curl`
user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

get_tz() {
	SET_TZ=""
	[ -e "/etc/localtime" ] && return
	for tzfile in /etc/TZ /var/et/TZ
	do
		[ -e "$tzfile" ] || continue
		tz="$(cat $tzfile 2>/dev/null)"
	done
	[ -z "$tz" ] && return
	SET_TZ=$tz
}

start_vnt2cli() {
	local cfg="$1"
	local enabled
	config_get_bool enabled "$cfg" 'enabled' '0'
	[ "$enabled" = "1" ] || return 1
	
	config_get clibin "$cfg" 'clibin'
	if [ -z "$clibin" ] ;then
		clibin=/tmp/vnt2_cli
	fi
	
	echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 開始啟動" >>/tmp/vnt2_cli.log
	echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 若啟動失敗，請打開 狀態 - 系統日誌 找到vnt2相關的字眼查看啟動失敗錯誤的原因" >>/tmp/vnt2_cli.log
	
	[ -z "`opkg list-installed | grep kmod-tun`" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 未安裝kmod-tun模塊，請確定安裝好kmod-tun " >>/tmp/vnt2_cli.log 
	
	path=$(dirname "$clibin")
	if [ -f /tmp/vnt2_cli ] && [ "${path:0:4}" != "/tmp" ] ;then
		mkdir -p $path
		chmod +x /tmp/vnt2_cli
		echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 找到上傳的程序/tmp/vnt2_cli，替換為$clibin " >>/tmp/vnt2_cli.log
		upsize="$(du -k /tmp/vnt2_cli | cut -f1)"
		result=$(expr $size - $upsize)
		if [ "$(($(/tmp/vnt2_cli -h 2>&1 | wc -l)))" -gt 3 ] && [ "$result" -gt 500 ] ; then
			mv -f /tmp/vnt2_cli "$clibin"
		else
			[ -z "$size" ] && [ "$(($(/tmp/vnt2_cli -h 2>&1 | wc -l)))" -gt 3 ] && mv -f /tmp/vnt2_cli "$clibin"
			echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 無法替換，上傳的程序不完整或自定義路徑的可用空間不足，當前空間剩餘${size}kb" >>/tmp/vnt2_cli.log
		fi
	fi
	
	if [ ! -f "$clibin" ] && [ "$size" -lt 4000 ] && [ ! -z "$size" ] ; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 自定義程序路徑的可用空間不足，自動切換為內存/tmp/vnt2_cli" >>/tmp/vnt2_cli.log
		sed -i "/clibin/ c option clibin '/tmp/vnt2_cli' " /etc/config/vnt2 
		clibin=/tmp/vnt2_cli
	fi
	
	if [ "$($clibin -h 2>&1 | wc -l)" -lt 3 ] || [ ! -f "$clibin" ] ; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 未找到程序 $clibin 開始在線下載" >>/tmp/vnt2_cli.log
		mkdir -p "$path"
		tag="$( curl -Lk --connect-timeout 5 --user-agent "$user_agent" -s  https://api.github.com/repos/vnt-2/vnt-2/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
		[ -z "$tag" ] && tag="v1.0.0"
		
		case "${cpucore}" in 
			"mipsle") url="mipsel-unknown-linux-musl"
			;;
			"mips") url="mips-unknown-linux-musl"
			;;
			"x86_64") url="x86_64-unknown-linux-musl"
			;;
			"i386") url="i686-unknown-linux-musl"
			;;
			"aarch64") url="aarch64-unknown-linux-musl"
			;;
			"armv7") url="armv7-unknown-linux-musleabi"
			;;
			"arm") url="arm-unknown-linux-musleabi"
			;;
		esac
		
		for proxy in $proxys ; do
			curl -Lko /tmp/vnt2_cli.tar.gz "${proxy}https://github.com/vnt-2/vnt-2/releases/download/${tag}/vnt2_cli-${url}-${tag}.tar.gz" || wget --no-check-certificate -O /tmp/vnt2_cli.tar.gz "${proxy}https://github.com/vnt-2/vnt-2/releases/download/${tag}/vnt2_cli-${url}-${tag}.tar.gz"
			if [ "$?" = 0 ] ; then
				tar -zxf /tmp/vnt2_cli.tar.gz -C $path
				rm -f /tmp/vnt2_cli.tar.gz >/dev/null 2>&1
				chmod +x "$clibin"
				if [ "$($clibin -h 2>&1 | wc -l)" -gt 3 ] ; then
					echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : ${clibin} 下載成功" >>/tmp/vnt2_cli.log
					break
				else
					uci -q set vnt2.@vnt2_cli[0].enabled=0
					uci commit vnt2
					echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : $clibin 下載失敗，請手動下載上傳程序,程序退出" >>/tmp/vnt2_cli.log
					return 1
				fi
			else
				echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : $clibin 下載失敗，請手動下載上傳程序,程序退出" >>/tmp/vnt2_cli.log
			fi
		done
	fi
	
	chmod +x "$clibin"
	ver="$($clibin -h 2>&1 | grep -i version | head -1 | awk '{print $1,$2}')"
	[ ! -z "$ver" ] && echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : ${clibin}當前版本號-${ver} " >>/tmp/vnt2_cli.log
	
	ps | grep 'vnt2_cli' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
	ps | grep 'vnt2_cli' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	
	local server network_code ipaddr mtu desvice_id localadd log password
	local peeradd desvice_name no__nat no_tun rtx compress fec
	local punch tunnel_port ctrl_port mapping allow_mapping
	local cert_mode no_punch udp_stun tcp_stun tunname
	
	config_get server "$cfg" 'server'
	config_get network_code "$cfg" 'network_code'
	config_get ipaddr "$cfg" 'ipaddr'
	config_get mtu "$cfg" 'mtu'
	config_get desvice_id "$cfg" 'desvice_id'
	config_get desvice_name "$cfg" 'desvice_name'
	config_get password "$cfg" 'password'
	config_get tunname "$cfg" 'tunname'
	config_get tunnel_port "$cfg" 'tunnel_port'
	config_get ctrl_port "$cfg" 'ctrl_port'
	config_get cert_mode "$cfg" 'cert_mode'
	config_get localadd "$cfg" 'localadd'
	config_get peeradd "$cfg" 'peeradd'
	config_get mapping "$cfg" 'mapping'
	config_get udp_stun "$cfg" 'udp_stun'
	config_get tcp_stun "$cfg" 'tcp_stun'
	
	config_get_bool log "$cfg" 'log' '0'
	config_get_bool no__nat "$cfg" 'no__nat' '0'
	config_get_bool no_tun "$cfg" 'no_tun' '0'
	config_get_bool rtx "$cfg" 'rtx' '0'
	config_get_bool compress "$cfg" 'compress' '0'
	config_get_bool fec "$cfg" 'fec' '0'
	config_get_bool no_punch "$cfg" 'no_punch' '0'
	config_get_bool allow_mapping "$cfg" 'allow_mapping' '0'
	
	if [ "$log" = "1" ] ;then
		if [ ! -f /tmp/vnt2_log.yaml ] ; then
			cat > /tmp/vnt2_log.yaml<<EOF
refresh_rate: 30 seconds
appenders:
  rolling_file:
    kind: rolling_file
    path: /tmp/vnt2_cli.log
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S vnt2_cli:)} [{f}:{L}] {h({l})} {M}:{m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 1 mb
      roller:
        kind: fixed_window
        pattern: /tmp/vnt2_cli.{}.log
        base: 1
        count: 2

root:
  level: info
  appenders:
    - rolling_file
EOF
		fi
	fi
	
	procd_open_instance "vnt2_cli"
	get_tz
	[ -z "$SET_TZ" ] || procd_set_param env TZ="$SET_TZ"
	procd_set_param command "$clibin"
	
	[ -z "$server" ] || procd_append_param command --server "$server"
	[ -z "$network_code" ] || procd_append_param command --network-code "$network_code"
	[ -z "$ipaddr" ] || procd_append_param command --ip "$ipaddr"
	[ -z "$mtu" ] || procd_append_param command --mtu "$mtu"
	[ -z "$desvice_id" ] || procd_append_param command --device-id "$desvice_id"
	[ -z "$desvice_name" ] || procd_append_param command --device-name "$desvice_name"
	[ -z "$password" ] || procd_append_param command --password "$password"
	[ -z "$tunname" ] || procd_append_param command --tun-name "$tunname"
	[ -z "$tunnel_port" ] || procd_append_param command --tunnel-port "$tunnel_port"
	[ -z "$ctrl_port" ] || procd_append_param command --ctrl-port "$ctrl_port"
	[ -z "$cert_mode" ] || procd_append_param command --cert-mode "$cert_mode"
	
	[ "$no_punch" = "1" ] && procd_append_param command --no-punch
	[ "$no_nat" = "1" ] && procd_append_param command --no-nat
	[ "$no_tun" = "1" ] && procd_append_param command --no-tun
	[ "$rtx" = "1" ] && procd_append_param command --rtx
	[ "$compress" = "1" ] && procd_append_param command --compress
	[ "$fec" = "1" ] && procd_append_param command --fec
	[ "$allow_mapping" = "1" ] && procd_append_param command --allow-mapping
	
	if [ ! -z "$localadd" ] ; then
		for localaddr in $(echo "$localadd" | tr ',' '\n'); do
			procd_append_param command --input "$localaddr"
		done
	fi
	
	if [ ! -z "$peeradd" ] ; then
		for peeraddr in $(echo "$peeradd" | tr ',' '\n'); do
			procd_append_param command --output "$peeraddr"
		done
	fi
	
	if [ ! -z "$mapping" ] ; then
		for map in $mapping; do
			procd_append_param command --port-mapping "$map"
		done
	fi
	
	if [ ! -z "$udp_stun" ] ; then
		for stun in $udp_stun; do
			procd_append_param command --udp-stun "$stun"
		done
	fi
	
	if [ ! -z "$tcp_stun" ] ; then
		for stun in $tcp_stun; do
			procd_append_param command --tcp-stun "$stun"
		done
	fi
	
	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="10000 10000"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
	
	if [ -z "$tunname" ] ; then
		vnt2_tun="vnt2-tun"
	else
		vnt2_tun="$tunname"
	fi 
	
	if [ ! -z "$(uci -q get network.VNT2)" ]; then
		uci set network.VNT2='interface'
		if [ -z "$ipaddr" ]; then
			uci set network.VNT2.proto='none'
		else
			uci set network.VNT2.proto='static'
			uci set network.VNT2.ipaddr=$ipaddr
			uci set network.VNT2.netmask='255.255.255.0'
		fi
		uci set network.VNT2.device=$vnt2_tun
		uci set network.VNT2.ifname=$vnt2_tun
		echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 添加網絡接口 VNT2 ，綁定虛擬網卡$vnt2_tun " >>/tmp/vnt2_cli.log
	fi
	
	if [ -z "$(uci -q get firewall.vnt2zone)" ]; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 添加防火牆規則，開啟IP動態偽裝 MSS鉗制" >>/tmp/vnt2_cli.log
		uci set firewall.vnt2zone='zone'
		uci set firewall.vnt2zone.input='ACCEPT'
		uci set firewall.vnt2zone.output='ACCEPT'
		uci set firewall.vnt2zone.forward='ACCEPT'
		uci set firewall.vnt2zone.masq='1'
		uci set firewall.vnt2zone.mtu_fix='1'
		uci set firewall.vnt2zone.name='VNT2'
		uci set firewall.vnt2zone.network='VNT2'
	fi
	
	[ -n "$(uci changes network)" ] && uci commit network && /etc/init.d/network reload >/dev/null 2>&1
	[ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1
	
	[ "$no_nat" = "0" ] && sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1
	
	echo `date +%s` > /tmp/vnt2_time
}

start_vnt2web() {
	local cfg="$1"
	local enabled
	config_get_bool enabled "$cfg" 'enabled' '0'
	[ "$enabled" = "1" ] || return 1
	
	config_get webbin "$cfg" 'webbin'
	if [ -z "$webbin" ] ;then
		webbin=/tmp/vnt2_web
	fi
	
	echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : 開始啟動" >>/tmp/vnt2_web.log
	echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : 若啟動失敗，請打開 狀態 - 系統日誌 找到vnt2相關的字眼查看啟動失敗錯誤的原因" >>/tmp/vnt2_web.log
	
	path=$(dirname "$webbin")
	if [ -f /tmp/vnt2_web ] && [ "${path:0:4}" != "/tmp" ] ;then
		mkdir -p $path
		chmod +x /tmp/vnt2_web
		echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : 找到上傳的程序/tmp/vnt2_web，替換為$webbin " >>/tmp/vnt2_web.log
		upsize="$(du -k /tmp/vnt2_web | cut -f1)"
		result=$(expr $size - $upsize)
		if [ "$(($(/tmp/vnt2_web -h 2>&1 | wc -l)))" -gt 3 ] && [ "$result" -gt 500 ] ; then
			mv -f /tmp/vnt2_web "$webbin"
		else
			[ -z "$size" ] && [ "$(($(/tmp/vnt2_web -h 2>&1 | wc -l)))" -gt 3 ] && mv -f /tmp/vnt2_web "$webbin"
			echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : 無法替換，上傳的程序不完整或自定義路徑的可用空間不足" >>/tmp/vnt2_web.log
		fi
	fi
	
	if [ ! -f "$webbin" ] && [ "$size" -lt 10000 ] && [ ! -z "$size" ] ; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : 自定義程序路徑的可用空間不足，自動切換為內存/tmp/vnt2_web" >>/tmp/vnt2_web.log
		uci -q set vnt2.@vnt2_web[0].webbin=/tmp/vnt2_web
		uci commit vnt2
		webbin=/tmp/vnt2_web
	fi
	
	if [ "$($webbin -h 2>&1 | wc -l)" -lt 3 ] || [ ! -f "$webbin" ] ; then
		echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : ${webbin} 不存在，開始在線下載" >>/tmp/vnt2_web.log
		mkdir -p "$path"
		tag="$( curl -Lk --connect-timeout 5 --user-agent "$user_agent" -s  https://api.github.com/repos/vnt-2/vnt-2/releases/latest  2>&1 | grep 'tag_name' | cut -d\" -f4 )"
		[ -z "$tag" ] && tag="v1.0.0"
		
		case "${cpucore}" in 
			"mipsle") url="mipsel-unknown-linux-musl"
			;;
			"mips") url="mips-unknown-linux-musl"
			;;
			"x86_64") url="x86_64-unknown-linux-musl"
			;;
			"i386") url="i686-unknown-linux-musl"
			;;
			"aarch64") url="aarch64-unknown-linux-musl"
			;;
			"armv7") url="armv7-unknown-linux-musleabi"
			;;
			"arm") url="arm-unknown-linux-musleabi"
			;;
		esac
		
		for proxy in $proxys ; do
			curl -Lko /tmp/vnt2_web.tar.gz "${proxy}https://github.com/vnt-2/vnt-2/releases/download/${tag}/vnt2_web-${url}-${tag}.tar.gz" || wget --no-check-certificate -O /tmp/vnt2_web.tar.gz "${proxy}https://github.com/vnt-2/vnt-2/releases/download/${tag}/vnt2_web-${url}-${tag}.tar.gz"
			if [ "$?" = 0 ] ; then
				tar -zxf /tmp/vnt2_web.tar.gz -C /tmp/
				chmod +x /tmp/vnt2_web
				rm -f /tmp/vnt2_web.tar.gz >/dev/null 2>&1
				if [ "$(($(/tmp/vnt2_web -h 2>&1 | wc -l)))" -gt 3 ] ; then
					echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : /tmp/vnt2_web 下載成功" >>/tmp/vnt2_web.log
					mv -f /tmp/vnt2_web "$webbin"
					break
				else
					uci -q set vnt2.@vnt2_web[0].enabled=0
					uci commit vnt2
					echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : $webbin 下載失敗，請手動下載上傳程序,程序退出" >>/tmp/vnt2_web.log
					return 1
				fi
			else
				echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : $webbin 下載失敗，請手動下載上傳程序,程序退出" >>/tmp/vnt2_web.log
			fi
		done
	fi
	
	chmod +x "$webbin"
	ps | grep 'vnt2_web' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
	ps | grep 'vnt2_web' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	
	local web_port webuser webpass logs web_wan
	config_get web_port "$cfg" 'web_port'
	config_get webuser "$cfg" 'webuser'
	config_get webpass "$cfg" 'webpass'
	config_get_bool logs "$cfg" 'logs' '0'
	config_get_bool web_wan "$cfg" 'web_wan' '0'
	
	procd_open_instance "vnt2_web"
	get_Tz
	[ -z "$SET_TZ" ] || procd_set_param env TZ="$SET_TZ"
	procd_set_param command "$webbin"
	
	[ -z "$web_port" ] || procd_append_param command --web-port "$web_port"
	[ -z "$webuser" ] || procd_append_param command --username "$webuser"
	[ -z "$webpass" ] || procd_append_param command --password "$webpass"
	
	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="10000 10000"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
	
	if [ "$web" = "1" ] && [ "$web_wan" = "1" ] ; then
		uci -q delete firewall.vnt2web
		uci set firewall.vnt2web=rule
		uci set firewall.vnt2web.name="vnt2_web"
		uci set firewall.vnt2web.target="ACCEPT"
		uci set firewall.vnt2web.src="wan"
		uci set firewall.vnt2web.proto="tcp"
		uci set firewall.vnt2web.dest_port="$web_port"
		uci set firewall.vnt2web.enabled="1"
	fi
	
	[ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1
}

stop_cli() {
	local cfg="$1"
	ps | grep 'vnt2_cli' | grep -v grep | awk '{print $1}' | xargs kill >/dev/null 2>&1
	ps | grep 'vnt2_cli' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	uci -q delete network.VNT2
	uci -q delete firewall.vnt2zone
	[ -n "$(uci changes network)" ] && uci commit network && /etc/init.d/network reload >/dev/null 2>&1
	[ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1
	rm -rf /tmp/vnt2_cli_*
	rm -rf /tmp/vnt2.tag
	echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_cli : 停止運行" >>/tmp/vnt2_cli.log
}

stop_web() {
	local cfg="$1"
	ps | grep 'vnt2_web' | grep -v grep | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	uci -q delete firewall.vnt2web
	[ -n "$(uci changes firewall)" ] && uci commit firewall && /etc/init.d/firewall reload >/dev/null 2>&1
	rm -rf /tmp/vnt2_web.log
	echo "$(date '+%Y-%m-%d %H:%M:%S') vnt2_web : 停止運行" >>/tmp/vnt2_web.log
}

start_service() {
	config_load 'vnt2'
	cputype=$(uname -ms | tr ' ' '_' | tr '[A-Z]' '[a-z]')
	[ -n "$(echo $cputype | grep -E "linux.*armv.*")" ] && cpucore="arm"
	[ -n "$(echo $cputype | grep -E "linux.*armv7.*")" ] && [ -n "$(cat /proc/cpuinfo | grep vfp)" ] && cpucore="armv7"
	[ -n "$(echo $cputype | grep -E "linux.*aarch64.*|linux.*armv8.*")" ] && cpucore="aarch64"
	[ -n "$(echo $cputype | grep -E "linux.*86.*")" ] && cpucore="i386"
	[ -n "$(echo $cputype | grep -E "linux.*86_64.*")" ] && cpucore="x86_64"
	if [ -n "$(echo $cputype | grep -E "linux.*mips.*")" ] ; then
		mipstype=$(echo -n I | hexdump -o 2>/dev/null | awk '{ print substr($2,6,1); exit}') 
		[ "$mipstype" = "0" ] && cpucore="mips" || cpucore="mipsle"
	fi
	proxys="https://github.moeyy.xyz/
	https://gh.llkk.cc/
	https://mirror.ghproxy.com/
	https://ghproxy.net/
	"
	config_foreach start_vnt2cli 'vnt2_cli'
	config_foreach start_vnt2web 'vnt2_web'
}

stop_service() {
	config_load 'vnt2'
	[ "$(uci -q get vnt2.@vnt2_web[0].enabled)" = "0" ] && stop_web 'vnt2_web'
	[ "$(uci -q get vnt2.@vnt2_cli[0].enabled)" = "0" ] && stop_cli 'vnt2_cli'
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "vnt2"
	procd_add_interface_trigger "interface.*.up" wan /etc/init.d/vnt2 reload
}
