name: Build-OpenWrt-VNT2

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: false
        default: ''

env:
  TAG: "${{ github.event.inputs.tag }}"
  TZ: Asia/Shanghai

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64_cortex-a53
          - arm_cortex-a7_neon-vfpv4
          - mipsel_24kc
        sdk:
          - openwrt-24.10

    steps:
      - uses: actions/checkout@v4
      - name: Build packages
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: vnt2
          PACKAGES: vnt2 vnts2 luci-app-vnt2
          NO_REFRESH_CHECK: true
          V: s
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VNT2-${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/vnt2/
